<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * @method static latest()
 * @method static create(array $array)
 */
class Career extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'slug',
        'desc',
        'status',
        'vacancy',
        'created_by',
        'updated_by',
    ];

    public function scopeStatus($query)
    {
        return $query->where('status', 1);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (Career $career) {
            $career->slug = slug($career->title);
            $career->created_by = Auth::id() ?? 1;
            $career->updated_by = Auth::id() ?? 1;
        });

        self::updating(function (Career $career) {
            $career->slug = slug($career->title);
            $career->updated_by = Auth::id();
        });
    }
}
