<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * @method static create(array $array)
 * @method static where(string $string, int $int)
 * @method static latest()
 * @method static status()
 * @method updateOrCreate(array $array)
 */
class ClientAndProduct extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'slug',
        'type',
        'serial',
        'description',
        'link',
        'status',
        'created_by',
        'updated_by',
    ];

    public function scopeStatus($query)
    {
        return $query->where('status', 1);
    }

    public function image()
    {
        return $this->morphMany(Image::class, 'imageable');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (ClientAndProduct $clientAndProduct) {
            $clientAndProduct->slug = slug($clientAndProduct->title);
            $clientAndProduct->created_by = Auth::id() ?? 1;
        });

        self::updating(function (ClientAndProduct $clientAndProduct) {
            $clientAndProduct->slug = slug($clientAndProduct->title);
            $clientAndProduct->updated_by = Auth::id();
        });
    }
}
