<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * @method static first()
 * @method static count()
 * @method static create(array $array)
 * @method static findOrFail($ourMission)
 * @method static status()
 */
class OurMission extends Model
{
    use HasFactory;
    protected $fillable = [
        'title_1',
        'title_2',
        'description_1',
        'description_2',
        'slug',
        'status',
        'created_by',
        'updated_by',
    ];

    public function scopeStatus($query)
    {
        return $query->where('status', 1);
    }

    public function createdUser()
    {
        return $this->belongsTo(Admin::class, 'created_by');
    }

    public function updatedUser()
    {
        return $this->belongsTo(Admin::class, 'updated_by');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($ourMission){
            $ourMission->created_by = Auth::id() ?? 1;
            $ourMission->slug = slug($ourMission->title_1);

        });
        static::updating(function ($ourMission){
            $ourMission->updated_by = Auth::id();
            $ourMission->slug = slug($ourMission->title_1);
        });
    }
}
