<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * @method static latest()
 * @method static create(array $array)
 * @method static where(string $string, $technology)
 * @method static status()
 */
class SkillOrTechnology extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'description',
        'slug',
        'serial',
        'status',
        'created_by',
        'updated_by',
    ];

    public function images()
    {
        return $this->morphMany(Image::class, 'imageable');
    }

    public function scopeStatus($query)
    {
        return $query->where('status', 1);
    }

    public function createdUser()
    {
        return $this->belongsTo(Admin::class, 'created_by');
    }

    public function updatedUser()
    {
        return $this->belongsTo(Admin::class, 'updated_by');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($skillOrTechnology){
            $skillOrTechnology->created_by = Auth::id() ?? 1;
            $skillOrTechnology->slug = slug(str_replace(['/',',','[',']','&'], '', $skillOrTechnology->title));
        });
        static::updating(function ($skillOrTechnology){
            $skillOrTechnology->updated_by = Auth::id();
            $skillOrTechnology->slug = slug(str_replace(['/',',','[',']'], '', $skillOrTechnology->title));
        });
    }
}
