<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * @method static latest()
 * @method static create(array $reply_details)
 */
class UserContactReply extends Model
{
    use HasFactory;
    protected $fillable = ['user_contact_id', 'reply_email', 'reply_subject', 'reply_message', 'created_by'];

    public function createdUser(){
        return $this->belongsTo(Admin::class, 'created_by');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($reply) {
            $reply->created_by = Auth::id() ?? 1;
        });
    }
}
