<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * @method static latest()
 * @method static create(array $array)
 * @method static findOrFail($userExpectation)
 * @method static status()
 */
class UserExpectation extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'quantity',
        'slug',
        'small_text',
        'status',
        'created_by',
        'updated_by',
    ];


    public function scopeStatus($query)
    {
        return $query->where('status', 1);
    }

    public function createdUser()
    {
        return $this->belongsTo(Admin::class, 'created_by');
    }

    public function updatedUser()
    {
        return $this->belongsTo(Admin::class, 'updated_by');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($userExpectation){
            $userExpectation->created_by = Auth::id() ?? 1;
            $userExpectation->slug = slug($userExpectation->title);

        });
        static::updating(function ($userExpectation){
            $userExpectation->updated_by = Auth::id();
            $userExpectation->slug = slug($userExpectation->title);
        });
    }
}
